version: "3.5"

services:
  erp_client:
    container_name: d_day_client
    image: d_day_client
    ports:
      - 7110:3110
    volumes:
      - ./app/client/:/app
    working_dir: /app
    command: "yarn install"
